stages:
  - Build
  - Deploy

include:
  - project: "tethys/kubernetes/gl-k8s-integration"
    ref: 1.6.1
    file: "/helm-check.yml"
  - project: "tethys/kubernetes/gl-k8s-integration"
    ref: 1.6.1
    file: "/kaniko-build.yml"

### Build ###
"Check Helm":
  stage: Build
  variables:
    HELM_CHART: $CI_PROJECT_DIR/helm/gsprestapi

"Update Helm":
  stage: Build
  variables:
    HELM_REPO_USERNAME: aquaveo
    HELM_CHART: $CI_PROJECT_DIR/helm/gsprestapi

"Build Tag":
  extends: .kaniko_build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    KANIKO_CONTEXT: $CI_PROJECT_DIR
    KANIKO_DOCKERFILE: $CI_PROJECT_DIR/Dockerfile
    KANIKO_DESTINATIONS: >
      eccr.ecmwf.int/geoglows_api/geoglows_api:$CI_COMMIT_TAG
      eccr.ecmwf.int/geoglows_api/geoglows_api:latest
  before_script:
    - >
      echo "{\"auths\":{
        \"$CI_REGISTRY\": {\"username\":\"$CI_REGISTRY_USER\", \"password\":\"$CI_REGISTRY_PASSWORD\"},
        \"eccr.ecmwf.int/harbor\": {\"username\":\"$ECCR_USER\", \"password\":\"$ECCR_PASSWORD\"}
      }}" > /kaniko/.docker/config.json
  only:
    - tags

"Build Stable":
  extends: .kaniko_build
  variables:
    KANIKO_CONTEXT: $CI_PROJECT_DIR
    KANIKO_DOCKERFILE: $CI_PROJECT_DIR/Dockerfile
    KANIKO_DESTINATIONS: eccr.ecmwf.int/geoglows_api/geoglows_api:stable
  before_script:
    - >
      echo "{\"auths\":{
        \"$CI_REGISTRY\": {\"username\":\"$CI_REGISTRY_USER\", \"password\":\"$CI_REGISTRY_PASSWORD\"},
        \"eccr.ecmwf.int/harbor\": {\"username\":\"$ECCR_USER\", \"password\":\"$ECCR_PASSWORD\"}
      }}" > /kaniko/.docker/config.json
  only:
    - /^stable$/

### DEPLOY ###
"Deploy to Staging":
  stage: Deploy
  image: aquaveollc/helm-docker:0.3.1
  dependencies: [] # Deploys do not depend on the Build phase artifacts
  variables:
    GIT_SUBMODULE_STRATEGY: none
  script:
    - echo ${CI_COMMIT_TAG}
    - 'curl -X POST -H "Authorization: Bearer ${ECCR_GEOGLOWS_TOKEN}" -d "bamboo.COMMIT_TAG=${CI_COMMIT_TAG}" https://bamboo.ecmwf.int/rest/api/latest/queue/GEOGLOWS-GSPRES0'

  when: manual
  only:
    - tags

"Deploy to Production":
  stage: Deploy
  image: aquaveollc/helm-docker:0.3.1
  dependencies: [] # Deploys do not depend on the Build phase artifacts
  variables:
    GIT_SUBMODULE_STRATEGY: none
  script:
    - echo ${CI_COMMIT_TAG}
    - 'curl -X POST -H "Authorization: Bearer ${ECCR_GEOGLOWS_TOKEN}" -d "bamboo.COMMIT_TAG=${CI_COMMIT_TAG}" https://bamboo.ecmwf.int/rest/api/latest/queue/GEOGLOWS-GSPRES1'

  when: manual
  only:
    - tags
