# Default values for gsprestapi.
# Declare variables to be passed into your templates.

replicaCount: 4

image:
  repository: "eccr.ecmwf.int/geoglows_api/geoglows_api"
  tag: latest
  pullPolicy: Always

imagePullSecrets:
- name: eccr-ecmwf-int
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: ov-issuer
    nginx.org/proxy-connect-timeout: 300s
    nginx.org/proxy-read-timeout: 300s
    nginx.org/proxy-send-timeout: 300s
  hosts:
  - host: geoglows.ecmwf.int
    paths:
    - path: /geoglows
      pathType: Prefix
      portName: http
  tls:
  - hosts:
    - geoglows.ecmwf.int
    secretName: geoglows-tls

resources:
  requests:
    cpu: 1
    memory: 1Gi
  limits:
    memory: 2Gi

nodeSelector: {}
tolerations: []
affinity: {}

persistentVolumes:
  geoglows-data-volume:
    mountPath: /mnt
    claimName: nfs-geoglows-prod-pvc

AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY: AWS_SECRET_ACCESS_KEY
AWS_LOG_GROUP_NAME: AWS_LOG_GROUP_NAME
AWS_LOG_STREAM_NAME: AWS_LOG_STREAM_NAME
AWS_REGION: AWS_REGION
